import archiver from 'archiver';
import { Response } from 'express';
import prisma from '../../db/prisma.client';
import { createError } from '../../middleware/error.middleware';

export async function streamProjectZip(projectId: string, res: Response): Promise<void> {
  // Try loading live files from project files first
  let files = await prisma.projectFile.findMany({
    where: { projectId, type: 'FILE' },
  });

  // Fallback: If no files in DB, check latest artifact
  if (files.length === 0) {
    const artifact = await prisma.artifact.findFirst({
      where:   { projectId, type: { in: ['FULL_BUILD', 'FRONTEND'] } },
      orderBy: { createdAt: 'desc' },
    });
    if (!artifact) throw createError('No generated files found for this project', 404);

    try {
      const payload = JSON.parse(artifact.content);
      const fileMap = payload.frontend ?? payload.files;
      if (fileMap) {
        files = Object.entries(fileMap).map(([filePath, content]) => ({
          path: filePath,
          content: content as string,
        })) as any;
      }
    } catch { /* skip */ }
  }

  if (files.length === 0) throw createError('No generated files found for this project', 404);

  const project = await prisma.project.findUnique({ where: { id: projectId } });
  const zipName  = `${(project?.name ?? 'archon-project').replace(/\s+/g, '-').toLowerCase()}.zip`;

  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${zipName}"`);

  const archive = archiver('zip', { zlib: { level: 9 } });
  archive.pipe(res);

  // Add generated source files
  for (const file of files) {
    if (file.content) {
      archive.append(file.content, { name: file.path });
    }
  }

  // Add package.json if not in generated files
  const hasPkg = files.some((f: any) => f.path === 'package.json');
  if (!hasPkg) {
    archive.append(JSON.stringify({
      name: zipName.replace('.zip', ''),
      version: '1.0.0',
      private: true,
      type: 'module',
      scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
      devDependencies: { '@vitejs/plugin-react': '^4.3.1', vite: '^5.4.0' },
    }, null, 2), { name: 'package.json' });
  }

  // Add vite config
  archive.append(`import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\nexport default defineConfig({ plugins: [react()] })\n`, { name: 'vite.config.js' });

  // Add README
  archive.append(`# ${project?.name ?? 'Archon Project'}\n\nGenerated by [Archon](https://archon.dinez.in)\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`, { name: 'README.md' });

  // Add architecture docs (if latest artifact exists)
  const artifact = await prisma.artifact.findFirst({
    where:   { projectId, type: { in: ['FULL_BUILD', 'FRONTEND'] } },
    orderBy: { createdAt: 'desc' },
  });

  if (artifact) {
    try {
      const payload = JSON.parse(artifact.content) as { architecture?: Record<string, unknown> };
      if (payload.architecture) {
        archive.append(JSON.stringify(payload.architecture, null, 2), { name: 'docs/architecture.json' });
      }
    } catch { /* skip */ }
  }

  await archive.finalize();
}
